### ISSUE TITLE
[Feature Request] Better management of saved sets

### ISSUE THREAD

**Issue by cyndane31** [nerd-of-now/NCP-VGC-Damage-Calculator#12]
Was wondering if it would be possible to individually manage the saved sets. Even being able to export a list, manually edit them, and then reimport the list would work. Having it be an all or nothing makes it rough when your thinking/crafting a lot of sets at once, the list can get junked up pretty quickly, especially on mobile which is my primary use case. 

A secondary request would be the ability to copy a set from a paste and run calcs against it without saving it, but the first half would solve this issue I think. This would just be a QOL addition to avoid deleting sets after the fact, but if it's easier than the first, I think would also be hugely beneficial in the theorycrafting stage of team building.

**Comment by nerd-of-now** [comment]
Managing sets as in-depth and you're asking would take me a while to get to. There is some support for editing individual sets currently, albeit a bit clunky: if you use "Save Calc Set" and change "My Calc Set" to the set's name, it'll update the old set with whatever changes you've added.

**Comment by nerd-of-now** [comment]
Well, a year and a half later and I've added functionality for this. Just load in a saved set and you should see a button to delete the set by the Export Set button. https://github.com/nerd-of-now/NCP-VGC-Damage-Calculator/commit/29628a016891b1aab07af21eb8bdfd5590296142
