### ISSUE TITLE
Better overlay 

### ISSUE THREAD

**Issue by Arceus-god** [nerd-of-now/NCP-VGC-Damage-Calculator#14]
hello, would it be possible to register there in the future so that you can see all your sets in one overview?

**Comment by nerd-of-now** [comment]
I think I achieved this with this update: https://github.com/nerd-of-now/NCP-VGC-Damage-Calculator/commit/d75d818f626c0ddc504daf6c1c3ece8793d339d7

Let me know if you had something else in mind.
