### ISSUE TITLE
Gyarados sets default item and forme incorrectly

### ISSUE THREAD

**Issue by JKassiotis** [nerd-of-now/NCP-VGC-Damage-Calculator#15]
Hey there,

Noticed an issue where if you created a custom Gyarados set (ill leave an example below) and attemp to switch to that set, the Forme is forced into Mega-Gyarados, and the item is switched to Gyaradosite.

Steps to replicate:
1. Create Custom Set
2. Select new set.

Attempted Workarounds:
Exported custom set via the "Export Set" function, after changing the forme and item to the appropriate options. Did not work.

Example Set:
Gyarados @ Sitrus Berry
Ability: Intimidate
Level: 50
Tera Type: Flying
EVs: 244 HP / 252 Atk / 4 Def / 4 SpD / 4 Spe 
Adamant Nature
- Thunder Wave
- Waterfall
- Protect
- Helping Hand

**Comment by nerd-of-now** [comment]
That's an oversight on my part with how the Damage Calc handles some Mega Evolutions. I'll look into making it more intuitive, but for now it should display the set as it should be if you turn National Dex mode off.

**Comment by nerd-of-now** [comment]
Fixed 21d5de41534e00919dc58f64e7229e3b42a4a783
