### ISSUE TITLE
Cannot save calc set or export set (for SV VGC damage calculator)

### ISSUE THREAD

**Issue by maxwell-zeus** [nerd-of-now/NCP-VGC-Damage-Calculator#17]
Hi,

The save cal set or export set button does not seem to work. I am not sure if I am missing anything but I have refreshed my browser a couple of times but it still doesn't work.

Moreover, I would like to suggest if there is a way to like import a set from showdown since not all pre-sets based on the drop down list matches whatever I have from showdown. It is like using a blank set but instead of typing everything, there can be an import button.

Thanks.

**Comment by nerd-of-now** [comment]
Hey,

I'm not sure I understand what the issues you're experiencing are. The calc's "Save Calc Set" and "Export Set" buttons work on my end, and the calc does have an import button in the center panel, with a field to paste your set into (circled in pic).

![ImportHighlight](https://github.com/nerd-of-now/NCP-VGC-Damage-Calculator/assets/68018081/af84cb57-20e9-4ae3-97bd-c18db551108f)

**Comment by maxwell-zeus** [comment]
May I ask what browser are you using?

**Comment by maxwell-zeus** [comment]
My bad. I thought exporting will ask me to save it somewhere. Didn't realize it simply copies the set and you can paste it. Thanks for helping out.

**Comment by nerd-of-now** [comment]
If you're all set I'll close this issue. Just in case, I have only been able to test the calc in Chrome and Firefox.
