### ISSUE TITLE
Incorrect Sword of Ruin Interaction

### ISSUE THREAD

**Issue by Stalruth** [nerd-of-now/NCP-VGC-Damage-Calculator#18]
> 252 Atk Mold Breaker Sword of Ruin Ogerpon-Hearthflame Horn Leech (1.2x Mask Boost) vs. 4 HP / 0 Def Chien-Pao: 117-138 (75 - 88.4%) -- guaranteed 2HKO

Seems to assume that Mold Breaker negates Sword of Ruin's self-immunity, even though this is not the case.

> 252+ Atk Ogerpon-Wellspring Horn Leech (1.2x Mask Boost) vs. 4 HP / 0 Def Chien-Pao: 96-114 (61.5 - 73%) -- guaranteed 2HKO

This is the correct calc, different forme does not impact the damage.

[Pokemon Showdown's Calculator](https://calc.pokemonshowdown.com) has this implemented correctly.

**Comment by nerd-of-now** [comment]
Good catch, fixed in https://github.com/nerd-of-now/NCP-VGC-Damage-Calculator/commit/becac6d30293f07d5a66cdf684f0e36834ea2aee

Turns out it's explicitly ignored in game, as is As One, which was also missing.
