### ISSUE TITLE
Rocky helmet not working correctly

### ISSUE THREAD

**Issue by VigsenGaming** [nerd-of-now/NCP-VGC-Damage-Calculator#19]
The calc doesnt calculate the recoil from rocky helmet example. 252 Atk Mystic Water Urshifu-Rapid Strike Surging Strikes (3 hits) vs. 116 HP / 80 Def Clefable on a critical hit: 138-165 (74.5 - 89.1%) -- guaranteed 2HKO. After 1 grass knot from clefable the urshifu would die but the calc still says that Urshifu wins

**Comment by nerd-of-now** [comment]
The calculation is for Clefable, not Urshifu, so the Rocky Helmet chip damage isn't accounted for. This is intended.
