### ISSUE TITLE
Kyogre Groudon Default set

### ISSUE THREAD

**Issue by Tcman96** [nerd-of-now/NCP-VGC-Damage-Calculator#21]
Hi, currently the default form for kyogre and groudon are the primal forms. Would you be able to change it so the regular forms are the default set?

**Comment by nerd-of-now** [comment]
Is this for National Dex mode for SWSH/SV?

**Comment by Tcman96** [comment]
Oh, I didn’t realize that was selected. I’m sorry, thank you
