### ISSUE TITLE
Zap Cannon has incorrect BP value

### ISSUE THREAD

**Issue by avlando** [nerd-of-now/NCP-VGC-Damage-Calculator#22]
Zap Cannon is set as 100 BP, where it should be 120 BP (changed in Gen IV)

https://bulbapedia.bulbagarden.net/wiki/Zap_Cannon_(move)

**Comment by nerd-of-now** [comment]
Fixed https://github.com/nerd-of-now/NCP-VGC-Damage-Calculator/commit/53fe45d61d80c839a419300047c1f995e5eaae73
