### ISSUE TITLE
Chilling Water is missing the Technician Tera Boost 

### ISSUE THREAD

**Issue by avlando** [nerd-of-now/NCP-VGC-Damage-Calculator#24]
Chilling Water is missing the Technician Tera Boost when used by a Tera Pokemon

Without Tera

252+ SpA Mystic Water Kyogre Chilling Water vs. 236 HP / 116 SpD Amoonguss in Rain: 49-58 (22.3 - 26.4%) -- possible 5HKO after Sitrus Berry recovery

With Tera

252+ SpA Mystic Water Tera-Water Kyogre Chilling Water vs. 236 HP / 116 SpD Amoonguss in Rain: 66-78 (30.1 - 35.6%) -- 97.7% chance to 4HKO after Sitrus Berry recovery

35.6%/26.4% = ~1.33

There is only the ~1.33 boost from Tera, no power increase to 60 BP like with other moves lower than 60 BP

**Comment by nerd-of-now** [comment]
Nope, that calculation is right. The BP boost from Tera is the last BP modifier applied. Kyogre is holding a Mystic Water, an item that applies a BP modifier earlier and enough of one to make Chilling Water equal to 60 BP, so no Tera BP modifier is applied.
