### ISSUE TITLE
I saw a little issue.

### ISSUE THREAD

**Issue by Uahh** [nerd-of-now/NCP-VGC-Damage-Calculator#25]
This condition will always be “true”:
https://github.com/nerd-of-now/NCP-VGC-Damage-Calculator/blob/main/script_res/ap_calc.js#L664
should use "!="

**Comment by nerd-of-now** [comment]
If you're referring to the "!==", it is a more precise "!=" in JavaScript.

**Comment by nerd-of-now** [comment]
After going through it, the operator wasn't the issue; JavaScript just doesn't perform the operation as expected. The rest of the code's still follows the same logic, so I didn't catch it. Removing the code would work, but using jQuery's $.isEmptyObject() fixes the condition and seems to have better performance. https://github.com/nerd-of-now/NCP-VGC-Damage-Calculator/commit/f5a939e1ce78c224ed0fa5bb4694a34d8a3cac17
