### ISSUE TITLE
Facade damage is NaN

### ISSUE THREAD

**Issue by zinjanthr0pus** [nerd-of-now/NCP-VGC-Damage-Calculator#26]
Doesn't matter if it's status'd or not. See screenshot
![facade](https://github.com/nerd-of-now/NCP-VGC-Damage-Calculator/assets/103463846/9ebb2f66-eae6-4f42-ae25-e48ee5484b90)

EDIT: I encountered this on the ADV setting. It also happens in dpp, but not in bw or later.

**Comment by nerd-of-now** [comment]
Fixed 5a5f52fb70940cd921768b5542c09f82d929954c
