### ISSUE TITLE
Overcoat is listed twice on ability list

### ISSUE THREAD

**Issue by avlando** [nerd-of-now/NCP-VGC-Damage-Calculator#27]
![IMG_6170](https://github.com/nerd-of-now/NCP-VGC-Damage-Calculator/assets/111962061/daa337b7-f1ef-47ca-b855-3795b00eadc1)

**Comment by nerd-of-now** [comment]
Fixed d4e98830df97cb4513a6d3ad2f6978b3a387d55a
