### ISSUE TITLE
[Feature Request] National Dex Pokemon in S/V

### ISSUE THREAD

**Issue by ImmortalZypther** [nerd-of-now/NCP-VGC-Damage-Calculator#3]
I play the National Dex format in S/V, and it's hard to do quick calculations in the S/V generation without manually inputting every stat for a Pokémon that isn't in the calculator (like Manectric).

Could you possibly add these Pokémon to the calculator?

**Comment by ximuwang** [comment]
Hi, I'd love to do the work. Are there any guidelines for inputting the stats?

**Comment by nerd-of-now** [comment]
It'll come in the next update. This is a VGC-tailored damage calculator so the full list of Pokémon/moves/items are going to be separate for the list of Pokémon/moves/items that are actually available in Scarlet and Violet.

**Comment by nerd-of-now** [comment]
https://github.com/nerd-of-now/NCP-VGC-Damage-Calculator/commit/7f20e59d5e72d06337893d506317d330aa6f2ee7

Fixed in this commit here. Hopefully this helps!
