### ISSUE TITLE
National Dex Mode Bugs Items

### ISSUE THREAD

**Issue by ImmortalZypther** [nerd-of-now/NCP-VGC-Damage-Calculator#4]
Items bug out in National Dex mode, sometimes duplicating or disappearing entirely.
Attached are examples of duplicating items and Booster Energy disappearing.

![image](https://user-images.githubusercontent.com/21045587/208556753-8cc62d2b-9aab-442b-bbd1-c17dda372c72.png)
![image](https://user-images.githubusercontent.com/21045587/208557015-29112353-edb9-4e2f-96bf-5a453a770303.png)

**Comment by nerd-of-now** [comment]
https://github.com/nerd-of-now/NCP-VGC-Damage-Calculator/commit/29d8351018676682719df371c1718b884f1cc579
