### ISSUE TITLE
Multiscale isn't properly broken by multi-hit moves

### ISSUE THREAD

**Issue by ImmortalZypther** [nerd-of-now/NCP-VGC-Damage-Calculator#6]
Rock Blast should be doing at least 100% since Multiscale is broken with the first hit, but instead it does 68% at minimum.
I've only tested Population Bomb as well, but it has the same bug.
![image](https://user-images.githubusercontent.com/21045587/209565413-1bcfce4b-a82a-40c1-baae-bb517251f9f7.png)

**Comment by nerd-of-now** [comment]
I'll look at ways to adjust it. Weak Armor and Stamina have similar issues, and I don't really know how to approach them, but Multiscale/Shadow Shield I can at least think of a way to adjust.

**Comment by nerd-of-now** [comment]
The problem with using recursion is the number of elements needed to accurately calculate the larger number of hits growing exponentially (over a trillion in the worst case for Population Bomb). Funnily enough, since the triple hit moves are already recursive they'd be the easiest to implement.

**Comment by nerd-of-now** [comment]
That's what the squashMultiHit function in ko-chance.js tries to accomplish, but I don't think that would be very accurate with stat changes that occur after every hit. I'd need to research and ask around for potential fixes there.

**Comment by tzarii** [comment]
Have you tried using an FFT to calculate the damage distribution? You can convert the damage spread of each hit into a histogram with an array size of greater than double the max damage done over all the hits. Then you can take each of the arrays and run them through an FFT and pointwise multiply them and then invert the result to get a histogram of all the possible damage values. From there, you can calculate an exact chance to ohko.

**Comment by nerd-of-now** [comment]
Well, it took me 2 years to get around to it, but I have finally added this in for Multiscale and Shadow Shield. We'll see if I extend it to other cases like Stamina or Kee/Maranga Berry. https://github.com/nerd-of-now/NCP-VGC-Damage-Calculator/commit/3900dec59968f9eedf1034d5fa2b6ee4ef7ffe80
![image](https://github.com/user-attachments/assets/86b78efe-49f3-4a36-ba0c-fd6292bbd3b9)
