### ISSUE TITLE
Iron Ball is ignored in calculations

### ISSUE THREAD

**Issue by ImmortalZypther** [nerd-of-now/NCP-VGC-Damage-Calculator#7]
I believe the check for immunity returns the method call for the damage formula before the grounded check, so Iron Ball isn't taken into account. 

Also, I don't know if it's already implemented this way since I can't check, but Iron Ball should do 1x damage against flying types regardless of their other type in gens V+. In gen IV it works just by making them grounded.

**Comment by nerd-of-now** [comment]
Fixed in 0699d68e7872ce7d9f079e9cf4cd8f098986bc1e
