### ISSUE TITLE
[Feature Request] Add support for tera raid mechanics

### ISSUE THREAD

**Issue by ZeroRin** [nerd-of-now/NCP-VGC-Damage-Calculator#8]
In tera raid we may use cheer to boost attacks/defenses by 1.5x. Also it would be helpful if we can have a customize boss HP multiplier built in. with these features users don't have to do extra calculation like `1225.6% * 1.5 / 2500% = 73.6%` for tera-raid after running the calculator

**Comment by nerd-of-now** [comment]
This is a damage calculator meant for competitive play. Not only are Tera raids not a form of competitive play, but they're also so unique compared to other kinds of battles in the games that they could have their own application.

I will not be adding any Tera raid mechanics to this damage calculator, but I will look into making a separate damage calculator specifically for Tera raids.
