### ISSUE TITLE
Duplicate item listings regardless of National Dex mode or not

### ISSUE THREAD

**Issue by ImmortalZypther** [nerd-of-now/NCP-VGC-Damage-Calculator#9]
Some items are duplicated even in the default mode of the calculator. 
A quick skim over the list found Lagging Tail, Leek, and Razor Fang duplicates.

![image](https://user-images.githubusercontent.com/21045587/211172921-86ad5d77-a9a4-4c8a-9b06-7fa63ce7e3c3.png)
![image](https://user-images.githubusercontent.com/21045587/211172975-4b22785d-2de4-45b1-af09-d94cee746fac.png)

**Comment by nerd-of-now** [comment]
Fixed in 3c803c84b813207e47e06a83a60b38622e89208f
